.TH LUSCA-CGI 8 "October 2010" "Lusca CGI Interface" "Debian Linux"
.SH NAME
lusca-cgi \- CGI interface to lusca
.SH SYNOPSIS
.B /usr/lib/cgi-bin/squid-cgi
.SH DESCRIPTION
.B Squid-cgi
is a CGI program that can be used as a WWW-based frontend to the
squid/lusca object cache. It should be run as a CGI script through your
WWW server.
.PP
.SH "SEE ALSO"
.BR squid (8)
