@echo off
if exist %temp%\auth_modules.txt del %temp%\auth_modules.txt
:loop
echo %1 >> %temp%\auth_modules.txt
shift /1
if NOT "%1"=="" goto :loop
echo /* automatically generated by %0 %*
echo  * do not edit
echo  */
echo #include "squid.h"
for /F %%m in (%temp%\auth_modules.txt) do echo extern AUTHSSETUP authSchemeSetup_%%m;
echo void authSchemeSetup(void)
echo {
for /F %%m in (%temp%\auth_modules.txt) do echo 	authSchemeAdd("%%m", authSchemeSetup_%%m);
echo }
if exist %temp%\auth_modules.txt del %temp%\auth_modules.txt
