@echo off
if exist %temp%\store_modules.txt del %temp%\store_modules.txt
:loop
echo %1 >> %temp%\store_modules.txt
shift /1
if NOT "%1"=="" goto :loop
echo /* automatically generated by %0 %*
echo  * do not edit
echo  */
echo #include "squid.h"
for /F %%m in (%temp%\store_modules.txt) do echo extern STSETUP storeFsSetup_%%m;
echo void storeFsSetup(void)
echo {
for /F %%m in (%temp%\store_modules.txt) do echo 	storeFsAdd("%%m", storeFsSetup_%%m);
echo }
if exist %temp%\store_modules.txt del %temp%\store_modules.txt
